services:
  orbita-app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    restart: unless-stopped
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - 3000:3000
    networks:
      - orbita-net
    stdin_open: true
    tty: true

networks:
  orbita-net: