services:
  orbita-client:
    build:
      context: ./
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 3000:80
    networks:
      - orbita-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  orbita-net:
