services:
  orbita-client:
    build:
      context: ./
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 3000:80
    networks:
      - orbita-net

networks:
  orbita-net:
